name: getCrypto
description: A new Flutter project. Created by Slidy

publish_to: 'none' 

version: 1.0.0+1
 
scripts:
  build: flutter pub run build_runner build
  clear: flutter pub run build_runner clean
  build_delete: flutter pub run build_runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.10
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+4
  flutter_modular: 
  flutter:
    sdk: flutter

dev_dependencies:
  pull_to_refresh: 1.6.4
  mockito: ^4.1.3
  modular_codegen: 
  mobx_codegen: ^1.1.2
  build_runner: ^1.10.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/app/assets/images/cryptos/coinBase.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
